import { useEffect, useState } from 'react'
import { Loader2, TrendingDown, TrendingUp } from 'lucide-react'
import { fetchMarketSummary, type MarketBrief } from '../api/marketSummary'

// Idle-state right pane: an hourly AI "Stock market today" briefing — headline,
// desk byline + timestamp, real index/mover moves, and a narrative paragraph, in
// the style of a living MSN market wrap. The heavy work (Exa news + Yahoo quotes +
// LLM) runs in divagent and is cached ~hourly, so we just poll every 5 min while
// mounted. Shown only when no calendar row is selected — the per-row agent analysis
// takes over that space on click (unchanged).
export function MarketSnapshot() {
  const [brief, setBrief] = useState<MarketBrief | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const controller = new AbortController()

    async function load() {
      try {
        const next = await fetchMarketSummary(controller.signal)
        if (controller.signal.aborted) return
        setBrief(next)
        setError(null)
      } catch (err) {
        if (err instanceof DOMException && err.name === 'AbortError') return
        // Keep the last good briefing on screen; only surface an error if we have none.
        setError((err as Error).message)
      } finally {
        if (!controller.signal.aborted) setLoading(false)
      }
    }

    load()
    // Server caches hourly; a 5-min poll is enough to pick up the next refresh.
    const timer = window.setInterval(load, 5 * 60_000)
    return () => {
      controller.abort()
      window.clearInterval(timer)
    }
  }, [])

  const updated = brief?.updatedAt ? new Date(brief.updatedAt) : null

  return (
    <div className="market-brief">
      <p className="eyebrow" style={{ margin: 0 }}>
        Stock market today
      </p>

      {loading && !brief ? (
        <p className="agent-analysis-placeholder" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Loader2 className="spin" size={14} /> Summarizing the market…
        </p>
      ) : error && !brief ? (
        <p className="agent-analysis-placeholder">{error}</p>
      ) : brief ? (
        <>
          <h3 className="market-brief-headline">{brief.headline}</h3>

          {(brief.byline || updated) && (
            <p className="market-brief-byline">
              {brief.byline}
              {brief.byline && updated ? ' · ' : ''}
              {updated
                ? `Updated ${updated.toLocaleString(undefined, {
                    weekday: 'short',
                    month: 'short',
                    day: 'numeric',
                    hour: 'numeric',
                    minute: '2-digit',
                  })}`
                : ''}
            </p>
          )}

          {brief.movers.length ? (
            <ul className="mover-row">
              {brief.movers.map((m) => {
                const pct = m.changePercent
                const up = (pct ?? 0) >= 0
                const color = up ? 'var(--success)' : 'var(--error-text)'
                return (
                  <li key={m.symbol} className="mover-chip" title={m.label ?? m.symbol}>
                    <span className="mover-symbol">{m.symbol}</span>
                    {pct != null ? (
                      <span className="mover-change" style={{ color }}>
                        {up ? <TrendingUp size={11} /> : <TrendingDown size={11} />}
                        {`${up ? '+' : ''}${pct.toFixed(2)}%`}
                      </span>
                    ) : null}
                  </li>
                )
              })}
            </ul>
          ) : null}

          <p className="market-brief-body">{brief.summary}</p>

          {brief.model ? (
            <p className="ticker-sub" style={{ margin: '4px 0 0', fontSize: 11 }}>
              Generated by {brief.model}
            </p>
          ) : null}
        </>
      ) : null}
    </div>
  )
}
