import { ExternalLink, Loader2, Sparkles, TriangleAlert, X } from 'lucide-react'
import type { DividendAnalysis, RiskLabel } from '../api/analyze'
import type { CalendarItem } from '../api/calendar'
import type { Dividend } from '../types/dividend'
import { formatCurrency, formatDate } from '../utils/formatters'

const RISK_COLOR: Record<RiskLabel, string> = {
  low: 'var(--success)',
  medium: 'var(--brand-dark)',
  high: 'var(--error-text)',
  unknown: 'var(--muted)',
}

export function SidePanel({
  watchlist,
  highestYield,
  onSelectSymbol,
  selectedItem,
  onClearSelection,
  analysis,
  analysisLoading = false,
  analysisError = null,
}: {
  watchlist: string[]
  highestYield?: Dividend
  onSelectSymbol: (symbol: string) => void
  selectedItem?: CalendarItem | null
  onClearSelection?: () => void
  analysis?: DividendAnalysis | null
  analysisLoading?: boolean
  analysisError?: string | null
}) {
  return (
    <aside className="side-panel">
      {selectedItem ? (
        <div className="agent-analysis">
          <div className="agent-analysis-head">
            <span className="eyebrow" style={{ margin: 0 }}>
              <Sparkles size={13} style={{ verticalAlign: '-2px', marginRight: 4 }} />
              Agent analysis
            </span>
            {onClearSelection ? (
              <button type="button" className="agent-analysis-close" onClick={onClearSelection} aria-label="Close analysis">
                <X size={16} />
              </button>
            ) : null}
          </div>

          <h3 style={{ margin: '2px 0 0' }}>{selectedItem.symbol}</h3>
          <p className="ticker-sub" style={{ margin: 0 }}>
            Ex-date {formatDate(selectedItem.exDate)}
            {selectedItem.amount != null ? ` · ${formatCurrency(selectedItem.amount)}` : ''}
          </p>

          <div className="agent-analysis-body">
            {analysisLoading ? (
              <p className="agent-analysis-placeholder" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Loader2 className="spin" size={16} /> Gemini is analyzing {selectedItem.symbol}…
              </p>
            ) : analysisError ? (
              <p className="agent-analysis-placeholder" style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--error-text)' }}>
                <TriangleAlert size={16} /> {analysisError}
              </p>
            ) : analysis ? (
              <>
                {analysis.headline ? (
                  <p style={{ margin: '0 0 8px', fontWeight: 600 }}>{analysis.headline}</p>
                ) : null}

                {analysis.riskLabel && analysis.riskLabel !== 'unknown' ? (
                  <span
                    style={{
                      display: 'inline-block',
                      padding: '2px 8px',
                      borderRadius: 999,
                      fontSize: 12,
                      fontWeight: 600,
                      marginBottom: 8,
                      color: RISK_COLOR[analysis.riskLabel],
                      border: `1px solid ${RISK_COLOR[analysis.riskLabel]}`,
                    }}
                  >
                    {analysis.riskLabel} reliability
                  </span>
                ) : null}

                <p className="agent-analysis-label">Reasoning</p>
                <p style={{ margin: '0 0 8px', whiteSpace: 'pre-wrap', lineHeight: 1.5 }}>
                  {analysis.reasoning}
                </p>

                {analysis.sources.length ? (
                  <>
                    <p className="agent-analysis-label">Sources</p>
                    <ul style={{ margin: 0, paddingLeft: 16 }}>
                      {analysis.sources.map((source, index) => (
                        <li key={`${source.url}-${index}`} style={{ marginBottom: 4 }}>
                          <a
                            href={source.url}
                            target="_blank"
                            rel="noreferrer"
                            style={{ color: 'var(--muted)', display: 'inline-flex', alignItems: 'center', gap: 4 }}
                          >
                            {source.title || source.url}
                            <ExternalLink size={12} />
                          </a>
                        </li>
                      ))}
                    </ul>
                  </>
                ) : null}

                {analysis.model ? (
                  <p className="ticker-sub" style={{ margin: '8px 0 0', fontSize: 11 }}>
                    Generated by {analysis.model}
                  </p>
                ) : null}
              </>
            ) : (
              <p className="agent-analysis-placeholder">No analysis available.</p>
            )}
          </div>
        </div>
      ) : null}

      <div>
        <p className="eyebrow">Saved symbols</p>
        <h3>Watchlist</h3>
      </div>
      {watchlist.length ? (
        <div className="watchlist">
          {watchlist.map((symbol) => (
            <button key={symbol} type="button" onClick={() => onSelectSymbol(symbol)}>
              {symbol}
            </button>
          ))}
        </div>
      ) : (
        <p>No symbols saved yet.</p>
      )}

      <div className="insight-card">
        <span>Highest yield</span>
        <strong>{highestYield?.symbol ?? 'N/A'}</strong>
      </div>

      <div>
        <p className="eyebrow">Market calendars</p>
        <div className="calendar-links">
          <a href="#">Earnings</a>
          <a href="#">IPO Calendar</a>
          <a href="#">Economic</a>
          <a href="#">Stock splits</a>
        </div>
      </div>
    </aside>
  )
}
